version: 2
jobs:
  build:
    working_directory: ~/pronto-bigfiles
    docker:
      - image: apiology/circleci-ruby:latest
    steps:
      - checkout
      - type: cache-restore
        key: pronto-bigfiles-{{ checksum "pronto-bigfiles.gemspec" }}-{{ checksum "Gemfile" }}
      # https://bundler.io/blog/2019/05/14/
      #   solutions-for-cant-find-gem-bundler-with-executable-bundle.html
      - run: gem update --system
      - run: gem install bundler
      - run: bundle install --path vendor/bundle --jobs=4
      - run: bundle exec rake --jobs=4 ci
      - type: cache-save
        key: pronto-bigfiles-{{ checksum "pronto-bigfiles.gemspec" }}-{{ checksum "Gemfile" }}
        paths:
          - "vendor/bundle"
